[package]
name = "gib-patch"
version = "0.0.0"
edition = "2024"
publish = false

license.workspace = true
[dependencies]
gib-hash.workspace = true
gib-object.workspace = true
gib-xdiff.workspace = true
jiff.workspace = true

[dev-dependencies]
futures = { workspace = true, features = ["async-await", "executor"] }
gib-diff.workspace = true
gib-fs.workspace = true
gib-odb.workspace = true
gib-testkit.workspace = true
