[package]
name = "webgit"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
git-async = { path = "./git-async" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Window",
    "Location",
    "Document",
    "HtmlDocument",
    "Element",
    "HtmlElement",
    "HtmlInputElement",
    "NodeList",
    "DomTokenList",
    "DomParser",
    "SupportedType",
    "Event",
    "EventTarget",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Headers",
    "console",
    "IdbDatabase",
    "IdbFactory",
    "IdbObjectStore",
    "IdbObjectStoreParameters",
    "IdbOpenDbRequest",
    "IdbRequest",
    "IdbTransaction",
    "IdbTransactionMode",
    "IdbVersionChangeEvent",
] }
chrono = "0.4"
console_error_panic_hook = "0.1"
serde = { version = "1", features = ["derive"] }
tera = { version = "2.0.0-alpha", default-features = false, features = ["unicode"] }
