[package]
name = "gib"
version = "0.0.0"
edition = "2024"
publish = false
description = "An async-first library for reading git repositories"
license = "MIT OR Apache-2.0"

[dependencies]
gib-commitgraph.workspace = true
gib-diff.workspace = true
gib-fs.workspace = true
gib-hash.workspace = true
gib-object.workspace = true
gib-odb.workspace = true
gib-pack.workspace = true
gib-ref.workspace = true
miniz_oxide.workspace = true

[dev-dependencies]
futures = { workspace = true, features = ["async-await", "executor"] }
gib-testkit.workspace = true
